### ISSUE TITLE
Description on how this differs from the original paginator. 

### ISSUE THREAD

**Issue by jonathan-s** [bryanwweber/pelican-pagination#3]

**Comment by bryanwweber** [comment]
Honestly, I don't remember anymore. Looking at the code, it seems like probably something to do with featured articles and having the right number of articles in the remaining slots. I think the implementation is largely copied from Pelican itself, if you want to diff them 😅

**Comment by jonathan-s** [comment]
Thanks :). So I guess I should consider this repo archived in a sense (or at least for strictly personal use). Thanks for answering!

**Comment by bryanwweber** [comment]
I would say, if it works for you feel free to use it! I plan to keep it updated for as long as I'm using pelican for my website 😁
